# Generated by Django 3.2.7 on 2022-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('from_time', models.TimeField()),
                ('out_date', models.TimeField()),
                ('reason', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to=None)),
                ('granted', models.BooleanField(default=False)),
            ],
        ),
    ]
