# Generated by Django 3.0.8 on 2022-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('from_time', models.TimeField()),
                ('out_date', models.TimeField()),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('granted', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
