# Generated by Django 3.0.8 on 2022-03-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='roll_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
