# Generated by Django 3.2.7 on 2022-03-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
