# Generated by Django 3.0.8 on 2022-04-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerApp', '0002_auto_20220331_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
