# Generated by Django 3.0.8 on 2022-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerApp', '0006_auto_20220403_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='out_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
