# Generated by Django 3.0.8 on 2022-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerApp', '0008_permission_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='branch',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
