# Generated by Django 3.0.8 on 2022-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerApp', '0010_auto_20220412_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='static/attachment'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='static/qr_code'),
        ),
    ]
