# Generated by Django 3.2.7 on 2022-03-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type_of_account',
            field=models.CharField(choices=[('STUDENT', 'student'), ('SECURITY', 'security'), ('ADMIN', 'admin'), ('SUPERADMIN', 'superadmin')], default='STUDENT', max_length=20),
        ),
    ]
