# Generated by Django 3.0.8 on 2022-03-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='grantedby',
        ),
    ]
