# Generated by Django 3.0.8 on 2022-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_remove_useraccount_grantedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='grantedby',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
