# Generated by Django 3.0.8 on 2022-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_useraccount_grantedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='parent_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='student_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
