# Generated by Django 3.2.7 on 2022-03-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_useraccount_is_superuser'),
        ('authentications', '0003_useraccount_grantedby'),
    ]

    operations = [
    ]
