# Generated by Django 3.0.8 on 2022-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_auto_20220404_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dp',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
