# Generated by Django 3.0.8 on 2022-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_auto_20220412_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dp',
            field=models.ImageField(null=True, upload_to='static/dp'),
        ),
    ]
